apiVersion: v1
kind: Pod 
metadata:
  labels:
    service: pod-af
  name: pod-af
spec:
  volumes:
  - name: shared-configs
    hostPath:
      path: /usr/config
  - name: shared-certs
    hostPath:
      path: /var/certs
  containers:
  - securityContext:
      privileged: false
    name: pod-af 
    image: af-image:1.0
    imagePullPolicy: Never
    command: [ "/bin/bash", "-c", "--" ]
    #args: [ "./entrypoint.sh" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 1Gi
    volumeMounts:
    - name: shared-data
      mountPath: /root/configs
    - name: shared-certs
      mountPath: /var/certs

  - securityContext:
      privileged: false
    name: nef-stub
    image: nef_stub-image:1.0
    imagePullPolicy: Never
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 1Gi
       volumeMounts:
    volumeMounts:
    - name: shared-data
      mountPath: /root/configs
    - name: shared-certs
      mountPath: /var/certs
        
  - securityContext:
      privileged: false
    name: cnca-stub
    image: cnca-image:1.0
    imagePullPolicy: Never
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    #args: [ "./entrypoint.sh" ]
    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 1Gi
    volumeMounts:
    - name: shared-data
      mountPath: /root/configs
    - name: shared-certs
      mountPath: /var/certs

  

