apiVersion: v1
kind: Pod
metadata:
  name: pod-nef
spec:
  containers:
  - securityContext:
      privileged: false
    name: nef-container 
    image: nef-image:1.0
    imagePullPolicy: Never
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 1Gi

  - securityContext:
      privileged: false
    name: af-stub-container
    image: af_stub-image:1.0
    imagePullPolicy: Never
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 1Gi


