apiVersion: v1
kind: Service
metadata:
  name: pod-nef
  labels:
    service: pod-nef
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: https
  selector:
    service: pod-nef
