apiVersion: v1
kind: Service
metadata:
  name: pod-af
  labels:
    service: pod-af
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    #nodePort: 30080
    protocol: TCP
    name: http
  selector:
    service: pod-af
