apiVersion: v1
kind: Service
metadata:
  name: afservice
  labels:
    service: afservice.ngc
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: cnca
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: nef   
  selector:
    service: afservice.ngc
