apiVersion: v1
kind: Service
metadata:
  name: nefservice
  labels:
    service: nefservice.ngc
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: af 
  selector:
    service: nefservice.ngc
