apiVersion: v1
kind: Pod 
metadata:
  name: oam.ngc
spec:
  volumes:
  - name: shared-configs
    hostPath:
      path: /etc/openness/configs/ngc
  - name: shared-certs
    hostPath:
      path: /etc/openness/certs/ngc
  containers:
  - securityContext:
      privileged: false
    name: oam-container 
    image: oam-image:1.0
    imagePullPolicy: Never
    command: [ "/bin/bash", "-c", "--" ]
    #args: [ "./entrypoint.sh" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 1Gi
    ports:
    - containerPort: 8083
      name: ui
    volumeMounts:
    - name: shared-configs
      mountPath: /etc/configs
    - name: shared-certs
      mountPath: /etc/certs
  tolerations:
  - key: node-role.kubernetes.io/master
    operator: "Exists"
    effect: "NoSchedule"
  nodeSelector:
    5g-openness: "true"
  restartPolicy: Always

